server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user_service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user_service/login
            - Method=POST
          filter:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user_service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user_service/users
            - Method=POST
          filter:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user_service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user_service/**
            - Method=GET
          filter:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user_service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog_service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order_service/**
